// ─────────────────────────────────────────────────────────────────────
// video/scripts/render-worker.ts — Long-running worker pour Phase 3
// ─────────────────────────────────────────────────────────────────────
// Poll le bot (GET /api/render-queue), render chaque job via Remotion
// (renderMedia programmatique), POST le MP4 multipart au bot pour
// upload Discord (POST /api/render-queue/:id/done).
//
// Lance avec : cd video && npm run worker
// Env vars requises : BOT_URL, RENDER_WORKER_TOKEN
// ─────────────────────────────────────────────────────────────────────

import { bundle } from '@remotion/bundler';
import { renderMedia, selectComposition } from '@remotion/renderer';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Job tel que renvoyé par le bot (camelCase déjà fait par jobToApiShape).
export type RenderJob = {
  id: number;
  ticker: string;
  entryAuthor: string;
  entryMessage: string;
  entryTimestamp: string;
  exitAuthor: string;
  exitMessage: string;
  exitTimestamp: string;
  pnl: string;
  // Optionnel : base64 PNG de l'image canvas-rendered (entry+exit
  // Discord conversation). Si null, la composition fallback sur les
  // Discord cards Remotion natives.
  proofImageBase64?: string | null;
  // Optionnel : base64 PNG du chart TradingView intraday du jour du trade,
  // avec callouts (flèches + labels) sur entry/exit. Fetché par le worker
  // via chart-img.com avant le render. Si null (API down ou pas de clé),
  // la composition skip la phase chart.
  chartImageBase64?: string | null;
  // Prix entry/exit extraits du message ou DB — requis pour positionner
  // les callouts sur le chart. Si manquants, le chart est fetché sans.
  entryPrice?: number | null;
  exitPrice?: number | null;
  // Optionnel : nom du template Remotion à utiliser (ex: "gold-celebration").
  // Si présent, le worker charge templates/<name>.json et merge ses props
  // comme base avant les props dynamiques du job.
  templateName?: string | null;
  // Composition Remotion à rendre (ex: 'ChartTemplate', 'BoomEntry'). Default
  // 'ChartTemplate'. Accepte aussi 'BoomProof' (ancien nom) pour rétrocompat
  // avec les jobs déjà en DB avant le rename.
  composition?: string;
  // JSON sérialisé contenant les props du récap (tickers, runnersHit, etc.).
  // Uniquement peuplé pour composition === 'BoomRecap'.
  recap_data?: string | null;
  // Tease text override (camelCase via jobToApiShape) — picker contextuel
  // décide ces valeurs au moment de l'enqueue. Si null, le worker utilise
  // les valeurs du template/defaultProps.
  teaseAction?: string | null;
  teaseSubtext?: string | null;
  // Mutated par processJob avant render quand composition === 'TobTradeRecap'.
  // Liste de paths staticFile relatifs (ex: 'recap-alerts/alert-1.png') où
  // les PNG d'alertes du jour ont été décodés depuis recap_data.alertImagesBase64.
  preparedAlertImages?: Array<{ imagePath: string; ticker?: string | null }>;
  // JSON sérialisé d'overrides arbitraires (ex: accentColor, ctaUrl) qu'on
  // merge SUR les props finales en priorité ultime. Sert au flow Video
  // Studio quand l'utilisateur tweak ces champs au moment du render.
  props_override?: string | null;
  // Data URL MP3 inline de la voix off (TTS ElevenLabs/Edge/Google).
  // Generated by processJob via generateTTS() avant render. La composition
  // consomme ce field si présent (<Audio> Remotion) et duck la BG music.
  narrationDataUrl?: string | null;
  // Texte de la narration. Si présent, la composition affiche aussi des
  // subtitles burned-in (NarrationSubtitles) pour autoplay muet TikTok.
  narrationText?: string | null;
};

// Charge un template JSON depuis video/templates/<name>.json.
// Retourne les props (objet) ou null si le template n'existe pas / invalide.
export function loadTemplateProps(name: string | null | undefined): Record<string, unknown> | null {
  if (!name) return null;
  const tplPath = path.join(__dirname, '..', 'templates', `${name}.json`);
  try {
    const raw = fs.readFileSync(tplPath, 'utf-8');
    const json = JSON.parse(raw);
    return (json && typeof json === 'object' && json.props) ? json.props : null;
  } catch (err) {
    console.warn(`[worker] template '${name}' load failed: ${err instanceof Error ? err.message : err}`);
    return null;
  }
}

// Parse le props_override JSON du job en objet sûr. Retourne {} si null/
// invalide pour ne jamais crasher le render à cause d'une override pourrie.
function parsePropsOverride(raw: string | null | undefined): Record<string, unknown> {
  if (!raw) return {};
  try {
    const obj = JSON.parse(raw);
    return obj && typeof obj === 'object' && !Array.isArray(obj) ? obj : {};
  } catch (err) {
    console.warn('[worker] props_override JSON invalid, ignored:', (err as Error).message);
    return {};
  }
}

// Props passées à la composition (sans le id, composition, et template
// côté DB qui ne sont pas des props Remotion).
// Ordre du merge : template props (base) ← job props ← image data URL
//                  ← props_override (top priority).
export function jobPropsToRemotion(job: RenderJob) {
  const { id: _id, composition: _comp, proofImageBase64, templateName, recap_data, props_override, narrationDataUrl, narrationText, ...rest } = job;
  const templateProps = loadTemplateProps(templateName) || {};
  const override = parsePropsOverride(props_override);
  // narrationDataUrl/Text ajoutés à toutes les compositions ; chacune
  // décide via sa Zod schema si elle les utilise (<Audio>, <NarrationSubtitles>).
  const narrationProps: { narrationDataUrl?: string | null; narrationText?: string | null } = {};
  if (narrationDataUrl) narrationProps.narrationDataUrl = narrationDataUrl;
  if (narrationText) narrationProps.narrationText = narrationText;

  // Pour BoomRecap : parse recap_data JSON et remplace les props.
  // Le worker ignore les entry_*/exit_* fields qui sont des placeholders
  // pour BoomRecap (la table render_jobs les exige NOT NULL pour rétrocompat).
  if (job.composition === 'BoomRecap' && recap_data) {
    try {
      const parsed = JSON.parse(recap_data);
      return {
        ...templateProps,
        ...parsed,  // overrides avec date, tickers, runners, tagline, totalGainPct
        ...narrationProps,
        ...override,
      };
    } catch (err) {
      console.error('[worker] Failed to parse recap_data:', (err as Error).message);
      // Continue avec template-only props (defaults sortiront depuis le schema Zod)
      return { ...templateProps, ...narrationProps, ...override };
    }
  }

  // Pour TobTradeRecap : recap_data porte le résultat OCR (dateLabel,
  // trades[], longTermInvestments[]) et optionnellement alertImagesBase64
  // — déjà décodés en fichiers PNG par processJob (cf preparedAlertImages
  // mutée sur `job`). On ignore les entry_*/exit_* (placeholders pour
  // satisfaire les NOT NULL columns).
  if (job.composition === 'TobTradeRecap' && recap_data) {
    try {
      const parsed = JSON.parse(recap_data);
      return {
        ...templateProps,
        dateLabel: parsed.dateLabel || 'TODAY',
        trades: parsed.trades || [],
        longTermInvestments: parsed.longTermInvestments || [],
        alertImages: job.preparedAlertImages || [],
        ...narrationProps,
        ...override,
      };
    } catch (err) {
      console.error('[worker] Failed to parse TobTradeRecap recap_data:', (err as Error).message);
      return { ...templateProps, ...narrationProps, ...override };
    }
  }

  // Else : flow existant (ChartTemplate, BoomEntry, etc.)
  // BoomEntry utilise entryImageDataUrl au lieu de proofImageDataUrl.
  // On expose les 2 keys pour que les 2 compositions puissent l'utiliser.
  const dataUrl = proofImageBase64
    ? `data:image/png;base64,${proofImageBase64}`
    : null;
  // Chart dataUrl séparé — fetched par fetchChartForJob avant processJob.
  // Reste null si chart-img KO, ChartTemplate skip la phase chart dans ce cas.
  const chartDataUrl = job.chartImageBase64
    ? `data:image/png;base64,${job.chartImageBase64}`
    : null;
  return {
    ...templateProps,
    ...rest,
    proofImageDataUrl: dataUrl,
    entryImageDataUrl: dataUrl,
    chartImageDataUrl: chartDataUrl,
    ...narrationProps,
    ...override,
  };
}

// ─── Chart fetch ──────────────────────────────────────────────────
// Pre-fetch le chart TradingView pour le job (ChartTemplate uniquement).
// Skip si :
//   - composition !== 'ChartTemplate' (et !== 'BoomProof' pour rétrocompat)
//   - CHART_IMG_API_KEY absent
//   - chart-img API échoue (timeout, 4xx, 5xx)
// Renvoie un base64 PNG ou null. Le worker ne FAIL PAS si chart-img KO,
// la composition est conçue pour skip la phase chart proprement.
//
// Symbol resolution : on essaie NASDAQ:TICKER en default (couvre la
// majorité des micro/small caps US). Si chart-img répond 404, on essaie
// AMEX. Pas de cache yahoo-finance ici pour rester rapide et autonome.
export async function fetchChartForJob(job: RenderJob): Promise<string | null> {
  const comp = job.composition || 'ChartTemplate';
  if (comp !== 'ChartTemplate' && comp !== 'BoomProof') return null;
  const apiKey = process.env.CHART_IMG_API_KEY;
  if (!apiKey) {
    console.warn(`[worker] job #${job.id}: CHART_IMG_API_KEY absent, skip chart`);
    return null;
  }

  // Import dynamique du client (JS depuis TS via require).
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { createChartImgClient, resolveSymbol } = require('../../discord/chart-img-client');

  const client = createChartImgClient({
    apiKey,
    width: 1080,    // matche le canvas vidéo 9:16
    height: 720,    // garde un ratio lisible (3:2)
    theme: 'dark',
  });

  // Format helper pour le label callout exit price (ex: "$0.202").
  const fmtPrice = (n: number): string => {
    if (n >= 100) return '$' + n.toFixed(2);
    if (n >= 1)   return '$' + n.toFixed(2);
    if (n >= 0.01) return '$' + n.toFixed(3);
    return '$' + n.toFixed(4);
  };

  // Construit les arrows (Arrow Mark Up / Down) si on a les prix.
  // Entry : flèche up + label 'When alerted' (pointe depuis le bas vers
  // le prix d'entrée). Exit : flèche down + label = exit price formaté
  // (pointe depuis le haut vers le prix de sortie).
  //
  // Offset 0.6% — entre 0.3% (touchait la candle) et 1% (trop loin).
  const arrows: Array<{
    datetime: string;
    price: number;
    text?: string;
    direction?: 'up' | 'down';
    fontBold?: boolean;
  }> = [];
  const ARROW_OFFSET = 0.006;

  if (Number.isFinite(job.entryPrice)) {
    arrows.push({
      datetime: job.entryTimestamp,
      price: (job.entryPrice as number) * (1 - ARROW_OFFSET),
      text: 'When alerted',
      direction: 'up',
      fontBold: true,
    });
  }
  if (Number.isFinite(job.exitPrice)) {
    arrows.push({
      datetime: job.exitTimestamp,
      price: (job.exitPrice as number) * (1 + ARROW_OFFSET),
      text: fmtPrice(job.exitPrice as number),
      direction: 'down',
      fontBold: true,
    });
  }

  const symbol = resolveSymbol(job.ticker, '');  // fallback NASDAQ
  try {
    const buf = await client.getChart(symbol, '1D', {
      studies: [],          // pas d'indicateurs (clean look)
      arrows,               // Arrow Mark Up/Down avec text labels
      // 'extended' pour AVOIR le pre-market data visible, mais avec un
      // bodyOverride paneProperties.background qui force le bg uniforme
      // (sinon TradingView ombrise les pre/after-market en plus foncé).
      session: 'extended',
      timezone: 'America/New_York',
      bodyOverride: {
        'paneProperties.background': '#131722',
        'paneProperties.backgroundType': 'solid',
        'paneProperties.backgroundGradientStartColor': '#131722',
        'paneProperties.backgroundGradientEndColor': '#131722',
      },
    });
    return buf.toString('base64');
  } catch (err) {
    console.warn(`[worker] job #${job.id}: chart-img failed for ${symbol}: ${(err as Error).message}`);
    return null;
  }
}

// Format heure NY 24h "HH:MM" depuis ISO timestamp.
export function formatTimeNY(isoTimestamp: string): string {
  const d = new Date(isoTimestamp);
  return d.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
    timeZone: 'America/New_York',
  });
}

// Format "+12.3%" / "-4.1%" pour les gains de trade.
function fmtPct(n: number): string {
  if (!Number.isFinite(n)) return '—';
  const sign = n >= 0 ? '+' : '';
  return `${sign}${n.toFixed(1)}%`;
}

// Format prix : 2-4 décimales selon magnitude (cohérent avec
// fmtPrice dans TobTradeRecap.tsx).
function fmtPrice(n: number): string {
  if (!Number.isFinite(n)) return '—';
  if (n >= 1) return n.toFixed(2);
  if (n >= 0.01) return n.toFixed(3);
  return n.toFixed(4);
}

// Caption pour les jobs TobTradeRecap : header + stats + liste des trades
// avec gains + section long-term. Construit pour rester sous la limite
// Discord de 2000 chars même avec 41 trades (testé ~1500 chars max).
export function buildTobTradeRecapCaption(parsed: any, fallbackDate: string): string {
  const trades = Array.isArray(parsed?.trades) ? parsed.trades : [];
  const lts = Array.isArray(parsed?.longTermInvestments) ? parsed.longTermInvestments : [];
  const date = parsed?.dateLabel || fallbackDate || 'TODAY';

  if (trades.length === 0) {
    return `🎬 **TOB Trade Recap — ${date}**\n(aucun trade dans le tableau)`;
  }

  const enriched = trades
    .map((t: any) => {
      const gainPct = ((t.hodPrice - t.entryPrice) / t.entryPrice) * 100;
      return {
        ticker: String(t.ticker || '').replace(/^\$+/, ''),
        entryPrice: t.entryPrice,
        hodPrice: t.hodPrice,
        gainPct,
      };
    })
    .filter((t: any) => Number.isFinite(t.gainPct));

  const green = enriched.filter((t: any) => t.gainPct > 0).length;
  const combined = enriched.reduce((s: number, t: any) => s + t.gainPct, 0);
  const avg = combined / Math.max(enriched.length, 1);
  const successRate = (green / Math.max(enriched.length, 1)) * 100;

  // Tri par gain desc pour highlight les meilleurs
  const sorted = [...enriched].sort((a: any, b: any) => b.gainPct - a.gainPct);
  const top3 = sorted.slice(0, 3);

  const lines: string[] = [];
  lines.push(`🎬 **TOB Trade Recap — ${date}**`);
  lines.push('');
  lines.push(`📊 ${enriched.length} trades · ${green}/${enriched.length} green (${successRate.toFixed(0)}%) · combined ${fmtPct(combined)} · avg ${fmtPct(avg)}`);
  lines.push('');

  if (top3.length > 0) {
    lines.push('🏆 **Top picks:**');
    for (const t of top3) {
      lines.push(`• \`$${t.ticker}\` ${fmtPct(t.gainPct)} (${fmtPrice(t.entryPrice)} → ${fmtPrice(t.hodPrice)})`);
    }
    lines.push('');
  }

  // Liste compacte de tous les trades en lignes condensées
  // ($TICKER +N% séparés par · jusqu'à ce que ça déborde, puis newline).
  lines.push('**All trades:**');
  const items = enriched.map((t: any) => `\`$${t.ticker}\` ${fmtPct(t.gainPct)}`);
  // Pack en lignes ≤ 90 chars pour rester lisible sur mobile.
  const packed: string[] = [];
  let row = '';
  for (const item of items) {
    if (row.length === 0) {
      row = item;
    } else if (row.length + 3 + item.length <= 90) {
      row += ' · ' + item;
    } else {
      packed.push(row);
      row = item;
    }
  }
  if (row) packed.push(row);
  lines.push(...packed);

  if (lts.length > 0) {
    lines.push('');
    lines.push('💎 **Long-term:**');
    for (const lt of lts) {
      const ltPct = ((lt.currentPrice - lt.entryPrice) / lt.entryPrice) * 100;
      const t = String(lt.ticker || '').replace(/^\$+/, '');
      lines.push(`• \`$${t}\` ${fmtPct(ltPct)} (${fmtPrice(lt.entryPrice)} → ${fmtPrice(lt.currentPrice)})`);
    }
  }

  let out = lines.join('\n');
  // Garde-fou : Discord coupe à 2000 chars. Si on dépasse, on tronque les
  // trades du milieu et on garde top picks + long-term intacts.
  if (out.length > 1990) {
    out = out.slice(0, 1980) + '\n… (truncated)';
  }
  return out;
}

// Caption Discord (multi-line). Exemple :
//   📈 $TSLA · Z · +20% — chart template
//   Entry 13:32 · Exit 16:30
//
// Utilise exitAuthor (l'analyste qui clôt le trade) plutôt que entryAuthor
// car ce dernier peut être un raw Discord username (ex "traderzz1m") moins
// joli que le display name relayé sur l'exit.
export function buildCaption(job: RenderJob): string {
  if (job.composition === 'TobTradeRecap') {
    let parsed: any = null;
    try {
      parsed = job.recap_data ? JSON.parse(job.recap_data) : null;
    } catch { /* swallow, fallback ci-dessous */ }
    return buildTobTradeRecapCaption(parsed, job.pnl);
  }
  return [
    `📈 $${job.ticker} · ${job.exitAuthor} · ${job.pnl} — chart template`,
    `Entry ${formatTimeNY(job.entryTimestamp)} · Exit ${formatTimeNY(job.exitTimestamp)}`,
  ].join('\n');
}

// Filename : YYYY-MM-DD_HHMM_TICKER_chart-template.mp4 (NY tz).
function buildLocalFilename(job: RenderJob): string {
  const d = new Date(job.exitTimestamp);
  const fmt = d.toLocaleString('en-CA', {
    timeZone: 'America/New_York',
    year: 'numeric', month: '2-digit', day: '2-digit',
    hour: '2-digit', minute: '2-digit', hour12: false,
  });
  const [datePart, timePart] = fmt.split(', ');
  const timeNoColon = timePart.replace(':', '');
  const suffix = job.composition === 'TobTradeRecap'
    ? 'tob-trade-recap'
    : 'chart-template';
  const tick = job.composition === 'TobTradeRecap'
    ? 'RECAP'
    : job.ticker.toUpperCase();
  return `${datePart}_${timeNoColon}_${tick}_${suffix}.mp4`;
}

// Décode les alertImagesBase64 (du recap_data) vers des data URLs inline.
// Pas d'écriture FS : on évite le pb du bundle Remotion qui snapshot
// public/ au boot du worker (fichiers écrits après ne sont pas servis,
// d'où les 404 sur alert-13.png et co).
//
// Retourne la liste des { imagePath: "data:image/png;base64,...", ticker }
// que la composition AlertsParadePhase consomme directement via <Img src>.
//
// `opts.publicDir` est gardé pour compat des tests mais ignoré (plus
// d'écriture FS).
export function prepareRecapAlertImages(
  recapDataJson: string | null | undefined,
  _opts: { publicDir?: string } = {},
): Array<{ imagePath: string; ticker?: string | null }> {
  void _opts; // kept for backward-compat signature
  if (!recapDataJson) return [];
  let parsed: { alertImagesBase64?: Array<{ base64: string; ticker?: string | null }> };
  try {
    parsed = JSON.parse(recapDataJson);
  } catch {
    return [];
  }
  const items = Array.isArray(parsed.alertImagesBase64) ? parsed.alertImagesBase64 : [];
  if (items.length === 0) return [];

  const out: Array<{ imagePath: string; ticker?: string | null }> = [];
  for (let i = 0; i < items.length; i++) {
    const it = items[i];
    if (!it || typeof it.base64 !== 'string' || !it.base64) continue;
    out.push({
      imagePath: `data:image/png;base64,${it.base64}`,
      ticker: it.ticker || null,
    });
  }
  return out;
}

// ─── Fonctions HTTP côté bot ─────────────────────────────────────────

async function fetchPendingJobs(botUrl: string, token: string): Promise<RenderJob[]> {
  const res = await fetch(`${botUrl}/api/render-queue`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!res.ok) throw new Error(`GET /api/render-queue failed: ${res.status}`);
  const body = await res.json() as { jobs?: unknown };
  if (!body || !Array.isArray(body.jobs)) {
    throw new Error('GET /api/render-queue returned malformed body (missing jobs array)');
  }
  return body.jobs as RenderJob[];
}

async function ackJobSuccess(
  botUrl: string, token: string, jobId: number,
  mp4Path: string, caption: string, ticker: string, exitTs: string,
) {
  const form = new FormData();
  const buf = fs.readFileSync(mp4Path);
  form.append('mp4', new Blob([buf], { type: 'video/mp4' }), path.basename(mp4Path));
  form.append('caption', caption);
  form.append('ticker', ticker);
  form.append('exitTs', exitTs);

  const res = await fetch(`${botUrl}/api/render-queue/${jobId}/done`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}` },
    body: form,
  });
  if (!res.ok) throw new Error(`POST /done failed: ${res.status} ${await res.text()}`);
  return res.json();
}

async function ackJobFailed(
  botUrl: string, token: string, jobId: number, errorMessage: string,
) {
  const res = await fetch(`${botUrl}/api/render-queue/${jobId}/done`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ error: errorMessage }),
  });
  if (!res.ok) {
    console.error(`[worker] failed to ACK error for job ${jobId}: ${res.status}`);
  }
}

// ─── Narration TTS pre-render ───────────────────────────────────────
// Génère le MP3 voice-over si activé, retourne le data URL ou null.
// Activation :
//   - env TOB_NARRATION_ENABLED=1 (global)
//   - OU props_override.enableNarration=true (per-job)
//
// Le texte est buildé par utils/narration.js (formules par composition),
// puis TTS via utils/gen-tts.js (multi-provider, ElevenLabs default).
//
// L'erreur TTS est silencieuse : la vidéo render sans voix off plutôt
// que de fail le job entier.
async function maybeGenerateNarration(job: RenderJob): Promise<{ dataUrl: string; text: string } | null> {
  const envEnabled = process.env.TOB_NARRATION_ENABLED === '1';
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { buildNarrationText } = require('../../utils/narration');
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { generateTTS } = require('../../utils/gen-tts');

  // Récupère le payload qui sert à construire le texte (recap_data parsed
  // pour TobTradeRecap/BoomRecap, sinon les fields directs de la row).
  let payload: any = job;
  if ((job.composition === 'TobTradeRecap' || job.composition === 'BoomRecap') && job.recap_data) {
    try { payload = JSON.parse(job.recap_data); } catch { /* fallback */ }
  }

  // Check le toggle per-job via props_override.
  let perJobEnabled = false;
  if (job.props_override) {
    try {
      const o = JSON.parse(job.props_override);
      if (o && o.enableNarration === true) perJobEnabled = true;
    } catch { /* swallow */ }
  }
  if (!envEnabled && !perJobEnabled) return null;

  const text = buildNarrationText(job.composition || 'ChartTemplate', payload);
  if (!text || text.length < 5) {
    console.log(`[worker] job #${job.id}: narration text empty, skipping TTS`);
    return null;
  }

  // Cap à 500 chars pour limiter le coût ElevenLabs et la durée audio
  // (~30s max à débit normal). Les formules génèrent ~100-200 chars donc
  // c'est large.
  const capped = text.length > 500 ? text.slice(0, 497) + '...' : text;

  // Output dans un tmp file (data URL après lecture).
  const tmpDir = path.join(__dirname, '..', 'out', '.narration-tmp');
  fs.mkdirSync(tmpDir, { recursive: true });
  const tmpFile = path.join(tmpDir, `narration-${job.id}-${Date.now()}.mp3`);

  try {
    await generateTTS({ text: capped, outputPath: tmpFile });
    const buf = fs.readFileSync(tmpFile);
    try { fs.unlinkSync(tmpFile); } catch { /* swallow */ }
    return {
      dataUrl: `data:audio/mpeg;base64,${buf.toString('base64')}`,
      text: capped,
    };
  } catch (err) {
    console.warn(`[worker] job #${job.id}: TTS failed (${(err as Error).message}) — vidéo sans voix off`);
    try { fs.unlinkSync(tmpFile); } catch { /* swallow */ }
    return null;
  }
}

// ─── Loop principal ─────────────────────────────────────────────────

async function processJob(
  job: RenderJob, bundleLocation: string, outDir: string,
  botUrl: string, token: string,
) {
  console.log(`[worker] processing job ${job.id} (${job.ticker} ${job.pnl})`);

  // Pre-fetch chart image (ChartTemplate uniquement, skip gracieusement si fail).
  // Augmente le job in-place pour que jobPropsToRemotion(job) le voie.
  const chartBase64 = await fetchChartForJob(job);
  if (chartBase64) {
    job.chartImageBase64 = chartBase64;
    console.log(`[worker] job #${job.id}: chart fetched (${(chartBase64.length * 0.75 / 1024).toFixed(0)} KB)`);
  }

  // Décode les PNG d'alertes pour TobTradeRecap (idempotent).
  if (job.composition === 'TobTradeRecap') {
    job.preparedAlertImages = prepareRecapAlertImages(job.recap_data);
    console.log(`[worker] job #${job.id}: prepared ${job.preparedAlertImages.length} alert PNGs`);
  }

  // Génère le TTS narration MP3 si activé (env TOB_NARRATION_ENABLED ou
  // job.props_override.enableNarration=true). Audio embed en data URL pour
  // contourner le bundle Remotion snapshot (cf alert PNGs). Le texte est
  // aussi attaché pour qu'il serve aux subtitles burned-in.
  // Best-effort : échec TTS = pas de voix off, mais video render OK.
  const narration = await maybeGenerateNarration(job);
  if (narration) {
    job.narrationDataUrl = narration.dataUrl;
    job.narrationText = narration.text;
    console.log(`[worker] job #${job.id}: narration MP3 generated (${(narration.dataUrl.length * 0.75 / 1024).toFixed(0)} KB data URL, ${narration.text.length} chars text)`);
  }

  // Aspect ratio variant : lit props_override.aspectRatio ('9x16'|'1x1'|
  // '16x9'). Default 9x16 (TikTok/Reels). Pour les autres ratios, on
  // suffix l'id de composition pour matcher les variants dans Root.tsx
  // (ex: TobTradeRecap → TobTradeRecap_1x1).
  const baseCompositionId = (job.composition === 'BoomProof' || !job.composition)
    ? 'ChartTemplate'
    : job.composition;
  let aspectRatio = '9x16';
  if (job.props_override) {
    try {
      const o = JSON.parse(job.props_override);
      if (o && (o.aspectRatio === '1x1' || o.aspectRatio === '16x9' || o.aspectRatio === '9x16')) {
        aspectRatio = o.aspectRatio;
      }
    } catch { /* swallow, use default */ }
  }
  const compositionId = aspectRatio === '9x16'
    ? baseCompositionId
    : `${baseCompositionId}_${aspectRatio}`;
  if (aspectRatio !== '9x16') {
    console.log(`[worker] job #${job.id}: rendering aspect ratio ${aspectRatio} → composition '${compositionId}'`);
  }

  const composition = await selectComposition({
    serveUrl: bundleLocation,
    id: compositionId,
    inputProps: jobPropsToRemotion(job),
  });
  const filename = buildLocalFilename(job);
  const outPath = path.join(outDir, filename);

  const renderStartedAt = Date.now();
  await renderMedia({
    composition,
    serveUrl: bundleLocation,
    codec: 'h264',
    outputLocation: outPath,
    inputProps: jobPropsToRemotion(job),
    // Cap bitrate pour rester sous la limite Discord (25 MB par défaut sur
    // serveur non-boosté). 3 Mbps × 20s ~= 7.5 MB, ample marge. La qualité
    // visuelle reste très bonne pour socials 1080×1920 (TikTok/Reels).
    // Sans cap, Remotion default (crf 18 = visually lossless) produit des
    // fichiers de 30-50 MB qui dépassent la limite Discord.
    videoBitrate: '3M',
  });
  const renderDurationMs = Date.now() - renderStartedAt;

  // Log file size pour debug. Discord accepte 25 MB par défaut (free),
  // 50 MB si Nitro Basic, 100 MB si Boost Level 3.
  const fileSizeMb = (fs.statSync(outPath).size / 1024 / 1024).toFixed(2);
  console.log(`[worker] rendered ${outPath} (${fileSizeMb} MB, ${(renderDurationMs / 1000).toFixed(1)}s)`);

  // Cost tracking — render local (gratuit en termes USD mais on track le
  // wall-clock time pour les analytics "combien de minutes de render/jour").
  // Best-effort, ne throw jamais. Import dynamique car render-worker tourne
  // dans un process séparé et le module peut ne pas être présent en CI.
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const { recordRender } = require('../../utils/cost-tracker');
    recordRender({
      durationMs: renderDurationMs,
      composition: compositionId,
      jobId: job.id,
      notes: { aspectRatio, fileSizeMb: Number(fileSizeMb) },
    });
  } catch (_) { /* swallow */ }

  // Caption Discord : si CAPTION_LLM_ENABLED=1 OU props_override.useLlmCaption,
  // demande à Claude (utils/caption-llm.js) de générer la caption à la place
  // de la formule template. Fallback safe à buildCaption si Anthropic KO.
  let captionText = buildCaption(job);
  const captionLlmEnvEnabled = process.env.CAPTION_LLM_ENABLED === '1';
  let perJobLlmEnabled = false;
  if (job.props_override) {
    try {
      const o = JSON.parse(job.props_override);
      if (o && o.useLlmCaption === true) perJobLlmEnabled = true;
    } catch { /* swallow */ }
  }
  if (captionLlmEnvEnabled || perJobLlmEnabled) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const { generateCaption } = require('../../utils/caption-llm');
      let payload: any = job;
      if ((job.composition === 'TobTradeRecap' || job.composition === 'BoomRecap') && job.recap_data) {
        try { payload = JSON.parse(job.recap_data); } catch { /* fallback */ }
      }
      const llmCaption = await generateCaption(job.composition || 'ChartTemplate', payload, 'discord');
      if (llmCaption && llmCaption.length > 10) {
        captionText = llmCaption;
        console.log(`[worker] job #${job.id}: caption LLM-generated (${llmCaption.length} chars)`);
      }
    } catch (err) {
      console.warn(`[worker] job #${job.id}: LLM caption failed (${(err as Error).message}) — falling back to template`);
    }
  }

  try {
    await ackJobSuccess(
      botUrl, token, job.id, outPath,
      captionText, job.ticker, job.exitTimestamp,
    );
    console.log(`[worker] job ${job.id} ACKed (Discord uploaded)`);
  } catch (err) {
    // Render succeeded but upload failed — the MP4 is on disk and recoverable.
    const msg = err instanceof Error ? err.message : String(err);
    throw new Error(`upload failed (MP4 saved at ${outPath}): ${msg}`);
  }
}

async function main() {
  const botUrl = process.env.BOT_URL;
  const token = process.env.RENDER_WORKER_TOKEN;
  if (!botUrl || !token) {
    console.error('[worker] FATAL: BOT_URL and RENDER_WORKER_TOKEN env vars required');
    process.exit(1);
  }

  const outDir = path.join(__dirname, '..', 'out', 'auto');
  fs.mkdirSync(outDir, { recursive: true });

  console.log('[worker] bundling Remotion project...');
  const bundleLocation = await bundle({
    entryPoint: path.join(__dirname, '..', 'src', 'index.ts'),
  });
  console.log(`[worker] ready, polling ${botUrl}/api/render-queue every 30s`);

  while (true) {
    try {
      const jobs = await fetchPendingJobs(botUrl, token);
      if (jobs.length === 0) {
        await sleep(30_000);
        continue;
      }
      console.log(`[worker] ${jobs.length} pending job(s)`);
      for (const job of jobs) {
        try {
          await processJob(job, bundleLocation, outDir, botUrl, token);
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          console.error(`[worker] job ${job.id} failed: ${msg}`);
          await ackJobFailed(botUrl, token, job.id, msg);
        }
      }
    } catch (err) {
      console.error('[worker] poll failed:', err instanceof Error ? err.message : err);
      await sleep(30_000);
    }
  }
}

function sleep(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

// Entrée du script (uniquement si exécuté directement, pas en test).
// Utilise pathToFileURL pour gérer les chemins Windows (backslashes) correctement.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch(err => {
    console.error('[worker] FATAL:', err);
    process.exit(1);
  });
}
